# fly.toml app configuration file generated for affirm on 2026-06-04T08:25:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'affirm'
primary_region = 'ewr'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  strategy = "immediate"

[machines]
  ha = false

[env]
  HTTP_PORT = '8080'
  RAILS_ENV = 'production'
  RAILS_LOG_TO_STDOUT = 'true'

[processes]
  app = "./bin/thrust ./bin/rails server"

[[mounts]]
  source = 'affirm_storage'
  destination = '/data'
  initial_size = '1gb'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
